# Generated by Django 3.2 on 2024-12-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_user_confirmation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=16, verbose_name='Код подтвержедния'),
        ),
    ]
